[package]
name = "cargo-distribution"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
cargo = "0.15"
rustc-serialize = "0.3"
docopt = "0.6"
tar = { version = "0.4", default_features = false }
flate2 = "0.2"
