[package]
name = "cargo-sls-distribution"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "Apache-2.0"
description = "A Cargo subcommand which packages a binary crate into a distribution archive"
repository = "https://github.com/sfackler/cargo-sls-distribution"
readme = "README.md"

[dependencies]
cargo = "0.15"
docopt = "0.6"
flate2 = "0.2"
git2 = { version = "0.6", default_features = false }
rustc-serialize = "0.3"
serde = "0.8"
serde_yaml = "0.5"
shell-escape = "0.1.1"
tar = { version = "0.4", default_features = false }
toml = { version = "0.2", default_features = false, features = ["serde"] }
